apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: backend-storage
  namespace: ian-lagat

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: gp3

  resources:
    requests:
      storage: 2Gi