apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: ian-lagat

spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${BACKEND_REPOSITORY}:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          volumeMounts:
            - name: backend-storage
              mountPath: /app/data
      volumes:
        - name: backend-storage
          emptyDir: {}
