name: Ian Lagat Capstone CI/CD

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  BACKEND_REPOSITORY: ${{ secrets.BACKEND_REPOSITORY }}
  FRONTEND_REPOSITORY: ${{ secrets.FRONTEND_REPOSITORY }}
  EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2


      - name: Build Backend Image
        run: |
          docker build -t backend ./backend

      - name: Tag Backend Image
        run: |
          docker tag backend:latest \
          ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${BACKEND_REPOSITORY}:latest

      - name: Push Backend Image
        run: |
          docker push \
          ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${BACKEND_REPOSITORY}:latest

      - name: Build Frontend Image
        run: |
          docker build -t frontend ./frontend

      - name: Tag Frontend Image
        run: |
          docker tag frontend:latest \
          ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${FRONTEND_REPOSITORY}:latest

      - name: Push Frontend Image
        run: |
          docker push \
          ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${FRONTEND_REPOSITORY}:latest



      - name: Install kubectl
        uses: azure/setup-kubectl@v4



      - name: Configure kubeconfig
        run: |
          aws eks update-kubeconfig \
          --region ${AWS_REGION} \
          --name ${EKS_CLUSTER_NAME}


      - name: Install gettext
        run: |
          sudo apt-get update
          sudo apt-get install -y gettext-base



      - name: Deploy Namespace
        run: |
          kubectl apply -f k8s/namespace.yaml


      - name: Deploy Backend
        run: |
          envsubst < k8s/deployment-backend.yaml | kubectl apply -f -



      - name: Deploy Backend Service
        run: |
          kubectl apply -f k8s/service-backend.yaml


      - name: Deploy Frontend
        run: |
          envsubst < k8s/deployment-frontend.yaml | kubectl apply -f -



      - name: Deploy Frontend Service
        run: |
          kubectl apply -f k8s/service-frontend.yaml


      - name: Deploy Ingress
        run: |
          kubectl apply -f k8s/ingress.yaml



      - name: Verify Deployment
        run: |
          kubectl get all -n ian-lagat